name: moon-affected
description: Returns a list of affected packages based on changed files
author: valpinkman
inputs:
  ref:
    description: "name of branch or ref to compare with (defaults to 'develop'). Git syntax allowed (HEAD^1)"
    default: develop
    required: false
outputs:
  affected:
    description: "Returns an array of affected packages (empty array if nothing has changed)"

runs:
  using: node16
  main: build/main.js

branding:
  icon: shuffle
  color: green
