$schema: "https://moonrepo.dev/schemas/tasks.json"
implicitInputs: []
tasks:
  build/libs:
    command: noop
    deps:
      - ~:build
    platform: node
  build:
    command: pnpm run --if-present build
    deps:
      - ^:build
    outputs:
      - "lib/"
      - "lib-es/"
    options:
      mergeOutputs: replace
    platform: node
